import { TITLE_CACHE } from './titlesCache';
/* Voorbeelddata (MVP) — later vervangen door Google Places, TMDB, bioscoop- en streaming-API's */
const CATS={bestellen:'Eten bestellen',uiteten:'Uit eten',koffie:'Koffie, lunch of brunch',film:'Film',serie:'Serie',bioscoop:'Bioscoop',activiteit:'Activiteit',borrel:'Borrel of café',uitgaan:'Uitgaan',dagje:'Dagje weg',sport:'Sportieve activiteit',workshop:'Creatieve workshop',thuis:'Thuisactiviteit',wellness:'Wellness',weekend:'Weekendtrip',vakantie:'Vakantie-idee',verrassing:'Verrassing'};
const LVLS={rustig:'Rustig',licht:'Licht actief',actief:'Actief',avontuur:'Avontuurlijk / intensief',gemengd:'Gemengd'};
const LVLEX={rustig:'Filmavond, uit eten, café, museum, bordspellen, wellness',licht:'Bowlen, poolen, minigolf, escape room, stadswandeling',actief:'Klimmen, padel, lasergamen, karten, kanoën',avontuur:'Crossmotor, survivalrun, mountainbiken, buggy rijden',gemengd:'Alle niveaus door elkaar'};
const MOODS={gezellig:'Gezellig en sociaal',ontspannen:'Rustig en ontspannen',romantisch:'Romantisch',creatief:'Creatief',competitief:'Competitief',avontuurlijk:'Avontuurlijk',luxe:'Luxe',laagdrempelig:'Laagdrempelig',spontaan:'Spontaan',cultureel:'Cultureel',eten:'Eten en drinken centraal',buiten:'Buiten zijn',binnen:'Binnen blijven',muziek:'Met muziek',kind:'Kindvriendelijk',team:'Teambuilding',leerzaam:'Leerzaam',feestelijk:'Feestelijk'};
const INTS={eten:'Eten en drinken',film:'Films en series',muziek:'Muziek en uitgaan',sport:'Sport en beweging',motor:'Auto, motor en techniek',games:'Games en competitie',natuur:'Natuur en buitenleven',cultuur:'Cultuur en geschiedenis',creatief:'Creatief en workshops',wellness:'Wellness en ontspanning',reizen:'Reizen en ontdekken',nacht:'Nachtleven en evenementen',familie:'Familie en kinderen',thuis:'Thuisactiviteiten',dieren:'Dieren en recreatie',seizoen:'Seizoensactiviteiten',tech:'Technologie en innovatie'};
const TRANS={lopen:'Lopen',fiets:'Fiets',auto:'Auto',motor:'Motor',ov:'Openbaar vervoer'};
const REACH={lopen:3,fiets:12,auto:250,motor:250,ov:80},SPEED={lopen:5,fiets:15,auto:45,motor:45,ov:25};
const DIETS={veg:'Vegetarisch',vegan:'Vegan',halal:'Halal',gluten:'Glutenvrij',lactose:'Lactosevrij',allergie:'Allergievriendelijk'};
const CUIS={hollands:'Hollands / eetcafé',italiaans:'Italiaans',pizza:'Pizza',burgers:'Burgers',friet:'Friet en snacks',chinees:'Chinees',aziatisch:'Aziatisch',sushi:'Sushi / Japans',thais:'Thais',indonesisch:'Indonesisch',indiaas:'Indiaas',turks:'Turks / kebab',grieks:'Grieks',libanees:'Libanees',mexicaans:'Mexicaans',tapas:'Tapas / Spaans',frans:'Frans',steak:'Steak / grill',vis:'Vis',pannenkoeken:'Pannenkoeken'};
const GENRES={actie:'Actie',avontuur:'Avontuur',komedie:'Komedie',drama:'Drama',thriller:'Thriller',scifi:'Sciencefiction',fantasy:'Fantasy',misdaad:'Misdaad',romantiek:'Romantiek',animatie:'Animatie',familie:'Familie',horror:'Horror',documentaire:'Documentaire',oorlog:'Oorlog',reality:'Reality'};
const GENRE_IDS={actie:[28,10759],avontuur:[12,10759],komedie:[35],drama:[18],thriller:[53,9648],scifi:[878,10765],fantasy:[14,10765],misdaad:[80],romantiek:[10749],animatie:[16],familie:[10751,10762],horror:[27],documentaire:[99],oorlog:[10752,10768],reality:[10764]};
const STREAMS={netflix:'Netflix',prime:'Prime Video'};
const RULES={unaniem:['Unaniem','Iedereen moet ja zeggen'],meerderheid:['Meerderheid','Een ingesteld percentage zegt ja'],veto:['Veto','Eén nee verwijdert een optie definitief'],koppel:['Koppelmatch','Alleen twee gekozen personen moeten matchen'],deadline:['Deadline','Bij afloop wint de optie met de meeste ja-stemmen'],willekeurig:['Willekeurig','De app kiest bij afloop uit alle opties met minstens 50% ja']};
const FOODCATS=['bestellen','uiteten','koffie'];
const GRAD={uiteten:['#ff7a59','#ffb36b'],bestellen:['#ff5f6d','#ffc371'],koffie:['#a0673a','#e2b07a'],film:['#3a1c71','#d76d77'],serie:['#2b2d6e','#6a5af9'],bioscoop:['#1f1147','#c0398c'],activiteit:['#4d3cff','#21c8f6'],borrel:['#d4145a','#fbb03b'],uitgaan:['#8e2de2','#ff3cac'],dagje:['#11998e','#38ef7d'],sport:['#0f9b8e','#7be495'],workshop:['#ee9ca7','#a77bf3'],thuis:['#5f2c82','#49a09d'],wellness:['#43c6ac','#a8e6cf'],weekend:['#134e5e','#71b280'],vakantie:['#2193b0','#6dd5ed'],verrassing:['#7b4dff','#ff6ec4']};
export const gradOf=o=>GRAD[o.c[0]]||GRAD.activiteit;
const TITLES=['Wat doen we vrijdagavond?','Film voor vanavond','Uit eten met de groep','Zondagmiddag plannen','Teamuitje plannen','Date night','Iets leuks doen in Venlo'];
const QUICK=['🔥 Lijkt mij leuk','💸 Te duur','📍 Te ver','🕒 Geen tijd','🍔 Heb ik zin in','😴 Liever rustig','💪 Mag actiever','🚗 Te ver rijden','🎉 Perfect idee'];

/* Voorbeelddata (MVP) — later vervangen door Google Places, TMDB, bioscoop- en streaming-API's */
const OPTS=[
{id:'pool',t:'Pool & Bites Venlo',e:'🎱',c:['activiteit','uiteten','borrel'],l:'licht',m:['gezellig','competitief','eten','binnen'],i:['games','eten'],io:'binnen',p:27,r:4.6,km:1.2,dur:150,d:'023456',h:[15,25],g:[2,12],b:0,alc:'opt',di:['veg'],desc:'Pooltafels, darts en een kaart vol bites. Spelen en eten aan dezelfde tafel.',menu:['Loaded nachos','Smashburger','Bitterballenplank']},
{id:'bowl',t:'Bowlen & Bites Strike',e:'🎳',c:['activiteit','uiteten'],l:'licht',m:['gezellig','competitief','eten','binnen'],i:['games','eten','sport'],io:'binnen',p:32,r:4.5,km:3.4,dur:150,h:[12,24],g:[2,16],b:1,di:['veg','gluten'],desc:'Twee uur bowlen met onbeperkt bittergarnituur en een hoofdgerecht naar keuze.',menu:['Spareribs','Vega burger','Friet en snacks']},
{id:'escape',t:'Escape Room Het Kluishuis',e:'🔐',c:['activiteit'],l:'licht',m:['competitief','team','gezellig','binnen'],i:['games'],io:'binnen',p:26,r:4.8,km:2.1,dur:75,h:[10,23],g:[2,6],b:1,desc:'Breek binnen 60 minuten uit een oude bankkluis. Samenwerken is de enige uitweg.',dress:'Geen voorbereiding nodig'},
{id:'golf',t:'Glow-in-the-dark minigolf',e:'⛳',c:['activiteit'],l:'licht',m:['gezellig','competitief','laagdrempelig','binnen'],i:['games'],io:'binnen',p:14,r:4.3,km:4.0,dur:60,h:[11,23],g:[2,10],b:0,kid:1,desc:'18 holes in blacklight met neonballen en een bar bij de laatste hole.'},
{id:'dobbel',t:'Spelletjesbar De Dobbelsteen',e:'🎲',c:['activiteit','borrel'],l:'rustig',m:['gezellig','competitief','laagdrempelig','binnen'],i:['games','eten'],io:'binnen',p:12,r:4.5,km:0.8,dur:180,d:'3456',h:[16,25],g:[2,10],b:0,alc:'opt',pet:1,kid:1,desc:'Meer dan 600 bordspellen, een spelleider die uitlegt en tosti\'s tot laat.'},
{id:'arcade',t:'Arcadehal Pixel Palace',e:'🕹️',c:['activiteit','uitgaan'],l:'licht',m:['competitief','gezellig','binnen','muziek'],i:['games','tech'],io:'binnen',p:20,r:4.2,km:1.5,dur:120,h:[13,24],g:[1,20],b:0,desc:'Retrokasten, air hockey en racegames. Speltegoed per persoon inbegrepen.'},
{id:'quiz',t:'Pizza & Pubquiz Café Maaskade',e:'🍕',c:['uiteten','borrel','activiteit'],l:'rustig',m:['gezellig','competitief','eten','binnen'],i:['eten','games'],io:'binnen',p:24,r:4.4,km:0.6,dur:180,d:'45',h:[19,23.5],g:[2,8],b:1,alc:'opt',di:['veg'],cu:'pizza',desc:'Elke donderdag en vrijdag: pizza per team en vijf quizrondes met prijzen.',menu:['Pizza margherita','Pizza salami','Vega pizza']},
{id:'spelsmaak',t:'Restaurant Spel & Smaak',e:'♟️',c:['uiteten','activiteit'],l:'rustig',m:['gezellig','eten','binnen','laagdrempelig'],i:['eten','games'],io:'binnen',p:31,r:4.5,km:2.8,dur:180,h:[17,23],g:[2,10],b:1,di:['veg','vegan','gluten'],cu:'tapas',desc:'Shared dining met een kast vol bordspellen aan tafel.',menu:['Shared plates','Vegan bao','Dame blanche']},
{id:'cocktail',t:'Cocktailworkshop Shake It',e:'🍸',c:['workshop','borrel','activiteit'],l:'rustig',m:['gezellig','creatief','feestelijk','binnen'],i:['eten','creatief'],io:'binnen',p:35,r:4.7,km:1.1,dur:120,d:'56',h:[19,23],g:[4,16],b:1,alc:'req',age:18,desc:'Een bartender leert je drie cocktails shaken. Mocktailvariant mogelijk.'},
{id:'tapas',t:'Tapas & Trivia',e:'🥘',c:['uiteten','activiteit'],l:'rustig',m:['gezellig','competitief','eten','binnen'],i:['eten','games'],io:'binnen',p:29,r:4.3,km:0.9,dur:150,d:'3456',h:[17,23],g:[2,12],b:1,di:['veg','gluten'],cu:'tapas',desc:'Onbeperkt tapas in rondes, met tussendoor triviavragen per tafel.',menu:['Patatas bravas','Gambas al ajillo','Albóndigas']},
{id:'cinediner',t:'Bioscoop met dinerarrangement',e:'🎬',c:['bioscoop','uiteten','activiteit'],l:'rustig',m:['gezellig','eten','binnen','romantisch'],i:['film','eten'],io:'binnen',p:34,r:4.4,km:3.0,dur:210,h:[17,24],g:[1,10],b:1,di:['veg'],desc:'Tweegangendiner in het filmcafé, daarna een film naar keuze.',times:['19:45','21:15']},
{id:'karaoke',t:'Karaokebox Venlo',e:'🎤',c:['uitgaan','activiteit'],l:'licht',m:['feestelijk','muziek','gezellig','binnen'],i:['muziek','nacht'],io:'binnen',p:18,r:4.1,km:1.3,dur:120,d:'456',h:[19,26],g:[3,12],b:1,alc:'opt',desc:'Privébox met 20.000 nummers en een belknop voor drankjes.'},
{id:'laser',t:'Lasergamen Arena Blerick',e:'🔦',c:['activiteit','sport'],l:'actief',m:['competitief','team','binnen'],i:['games','sport'],io:'binnen',p:22,r:4.5,km:5.5,dur:60,h:[12,23],g:[4,24],b:1,age:8,kid:1,desc:'Drie potjes in een doolhof van 800 m² met mist en lichteffecten.',dress:'Sportschoenen'},
{id:'padel',t:'Padel Center Venlo',e:'🎾',c:['sport','activiteit'],l:'actief',m:['competitief','team'],i:['sport'],io:'beide',p:15,r:4.6,km:3.8,dur:90,h:[8,23],g:[2,8],b:1,desc:'Baanhuur inclusief rackets en ballen. Overdekte en buitenbanen.',dress:'Sportkleding en zaalschoenen'},
{id:'klim',t:'Klimhal Boulderz',e:'🧗',c:['sport','activiteit'],l:'actief',m:['avontuurlijk','team','binnen'],i:['sport'],io:'binnen',p:16,r:4.7,km:6.0,dur:120,h:[10,23],g:[1,12],b:0,desc:'Boulderen zonder touw. Korte introductie voor beginners inbegrepen.',dress:'Sportkleding, klimschoenen te huur'},
{id:'kart',t:'Indoor karten Speedway',e:'🏎️',c:['activiteit','sport'],l:'actief',m:['competitief','avontuurlijk','binnen'],i:['motor','games','sport'],io:'binnen',p:39,r:4.4,km:9.0,dur:60,h:[12,23],g:[2,20],b:1,age:12,desc:'Grand-prixformat: training, kwalificatie en een race van 15 minuten.',dress:'Dichte schoenen'},
{id:'jump',t:'Trampolinepark Jump',e:'🤸',c:['sport','activiteit'],l:'actief',m:['feestelijk','kind','binnen','competitief'],i:['sport','familie'],io:'binnen',p:15,r:4.0,km:7.0,dur:90,h:[10,21],g:[1,30],b:1,kid:1,desc:'Trampolines, foam pit en een dodgeballveld.',dress:'Antislipsokken (te koop)'},
{id:'kano',t:'Kanoën op de Maas',e:'🛶',c:['sport','activiteit','dagje'],l:'actief',m:['avontuurlijk','buiten','team'],i:['natuur','sport','seizoen'],io:'buiten',p:25,r:4.5,km:4.5,dur:180,h:[9,18],g:[2,20],b:1,wx:1,pet:1,w:0,desc:'Peddel 12 km stroomafwaarts; een busje brengt je terug.',dress:'Kleding die nat mag worden'},
{id:'paint',t:'Paintball Venray',e:'🎯',c:['activiteit','sport'],l:'actief',m:['competitief','avontuurlijk','buiten','team'],i:['games','sport'],io:'buiten',p:37,r:4.3,km:24,dur:150,d:'0456',h:[10,18],g:[6,30],b:1,age:14,w:0,desc:'Bosveld met forten en scenariospellen. 200 balletjes inbegrepen.',dress:'Oude kleding'},
{id:'cross',t:'Crossmotor rijden Baarlo',e:'🏍️',c:['activiteit','sport'],l:'avontuur',m:['avontuurlijk','buiten'],i:['motor','sport'],io:'buiten',p:89,r:4.8,km:13,dur:180,d:'0456',h:[9,17],g:[2,12],b:1,age:16,w:0,desc:'Instructie en rijden op een zandcircuit. Motor en uitrusting inbegrepen.',dress:'Lange broek; uitrusting te leen'},
{id:'survival',t:'Survivalrun Maasduinen',e:'🪢',c:['sport','activiteit','dagje'],l:'avontuur',m:['avontuurlijk','team','buiten','competitief'],i:['sport','natuur'],io:'buiten',p:45,r:4.6,km:22,dur:240,d:'06',h:[9,17],g:[6,40],b:1,age:12,w:0,desc:'8 km door bos en water met 30 hindernissen.',dress:'Sportkleding die vies mag worden'},
{id:'mtb',t:'Mountainbiken Boschhuizerbergen',e:'🚵',c:['sport','dagje'],l:'avontuur',m:['avontuurlijk','buiten'],i:['sport','natuur'],io:'buiten',p:18,r:4.5,km:6,dur:180,h:[8,20],g:[1,12],b:0,wx:1,w:0,desc:'Rode route van 26 km, huurfietsen bij het startpunt.',dress:'Helm verplicht'},
{id:'buggy',t:'Buggy rijden Limburg',e:'🚙',c:['activiteit'],l:'avontuur',m:['avontuurlijk','competitief','buiten'],i:['motor'],io:'buiten',p:95,r:4.6,km:30,dur:150,d:'0456',h:[10,17],g:[2,10],b:1,age:18,w:0,desc:'Offroadtocht met tweepersoonsbuggy\'s door een groeve.',dress:'Rijbewijs B nodig'},
{id:'fiets',t:'Maasroute fietstocht (45 km)',e:'🚴',c:['sport','dagje'],l:'actief',m:['buiten','spontaan','team'],i:['natuur','sport'],io:'buiten',p:5,r:4.4,km:0,dur:240,h:[8,20],g:[1,50],b:0,wx:1,pet:1,w:0,desc:'Langs de Maas naar Arcen en terug, met een stop bij een theetuin.'},
{id:'stad',t:'Stadswandeling Venlo',e:'🏛️',c:['activiteit'],l:'licht',m:['cultureel','ontspannen','buiten','laagdrempelig'],i:['cultuur','reizen'],io:'buiten',p:0,r:4.2,km:0.5,dur:90,h:[8,22],g:[1,30],b:0,pet:1,kid:1,desc:'Zelfgeleide route langs vestingresten, het stadhuis en de Maaskade.'},
{id:'museum',t:'Museumrondleiding Maasoevers',e:'🖼️',c:['activiteit'],l:'rustig',m:['cultureel','leerzaam','ontspannen','binnen'],i:['cultuur'],io:'binnen',p:14,r:4.3,km:1.0,dur:90,d:'234560',h:[11,17],g:[1,20],b:0,desc:'Stille rondleiding langs moderne kunst uit de regio.'},
{id:'wijn',t:'Wijnproeverij Domaine Maasdal',e:'🍷',c:['activiteit','borrel'],l:'rustig',m:['luxe','gezellig','eten'],i:['eten'],io:'beide',p:32,r:4.6,km:11,dur:120,d:'560',h:[14,22],g:[4,20],b:1,alc:'req',age:18,desc:'Proef zes Limburgse wijnen met kaas en uitleg van de wijnboer.'},
{id:'hightea',t:'High tea Kasteel Ooijen',e:'🫖',c:['koffie'],l:'rustig',m:['luxe','romantisch','ontspannen','eten','binnen'],i:['eten'],io:'binnen',p:29,r:4.5,km:8,dur:120,h:[12,17],g:[2,10],b:1,di:['veg','gluten'],desc:'Etagères met scones, sandwiches en zoetigheden in een kasteelzaal.'},
{id:'brunch',t:'Brunchbar Ochtendgloren',e:'🥞',c:['koffie'],l:'rustig',m:['gezellig','laagdrempelig','eten'],i:['eten'],io:'binnen',p:17,r:4.6,km:0.7,dur:90,h:[8,16],g:[1,8],b:0,di:['veg','vegan','gluten','lactose'],kid:1,desc:'Pancakes, shakshuka en specialty coffee.',menu:['Shakshuka','Fluffy pancakes','Avocadotoast']},
{id:'koffie',t:'Koffiebar Bonen & Banket',e:'☕',c:['koffie'],l:'rustig',m:['ontspannen','laagdrempelig'],i:['eten'],io:'binnen',p:8,r:4.4,km:0.3,dur:45,h:[8,18],g:[1,8],b:0,di:['veg','vegan','gluten','lactose'],pet:1,desc:'Kleine koffiebar met zelfgebakken taart.'},
{id:'marco',t:'Trattoria Da Marco',e:'🍝',c:['uiteten'],l:'rustig',m:['gezellig','romantisch','eten','binnen'],i:['eten'],io:'binnen',p:32,r:4.5,km:0.9,dur:120,d:'023456',h:[17,23],g:[2,14],b:1,di:['veg'],cu:'italiaans',desc:'Huisgemaakte pasta en een houtoven. Klein, dus reserveren aanbevolen.',menu:['Tagliatelle al ragù','Burrata','Tiramisu']},
{id:'sushi',t:'Sushi Sora',e:'🍣',c:['uiteten','bestellen'],l:'rustig',m:['gezellig','eten','luxe','binnen'],i:['eten'],io:'binnen',p:35,r:4.6,km:1.4,dur:120,h:[17,22.5],g:[1,12],b:1,di:['veg','gluten'],cu:'sushi',del:1,desc:'All-you-can-eat sushi in rondes, ook te bezorgen.',menu:['Dragon roll','Sashimimix','Gyoza']},
{id:'smash',t:'Burgerbar Smash',e:'🍔',c:['uiteten','bestellen'],l:'rustig',m:['laagdrempelig','gezellig','eten','binnen'],i:['eten'],io:'binnen',p:19,r:4.3,km:0.5,dur:75,h:[12,23],g:[1,16],b:0,di:['veg','vegan','halal'],cu:'burgers',del:1,kid:1,desc:'Smashburgers, loaded fries en milkshakes.',menu:['Double smash','Vegan crispy','Truffelfriet']},
{id:'warung',t:'Warung Sambal',e:'🍛',c:['uiteten','bestellen'],l:'rustig',m:['gezellig','eten'],i:['eten'],io:'binnen',p:24,r:4.7,km:2.2,dur:90,d:'234560',h:[16,22],g:[1,10],b:0,di:['veg','vegan','halal','gluten'],cu:'indonesisch',del:1,desc:'Rijsttafel voor de hele tafel en afhaalboxen.',menu:['Rendang','Gado-gado','Saté ayam']},
{id:'mezze',t:'Beiroet Mezze',e:'🧆',c:['uiteten'],l:'rustig',m:['gezellig','eten'],i:['eten'],io:'binnen',p:27,r:4.6,km:1.7,dur:120,h:[17,23],g:[2,14],b:1,di:['veg','vegan','halal'],cu:'libanees',desc:'Mezze om te delen en een houtskoolgrill.',menu:['Hummus','Falafel','Shish taouk']},
{id:'napoli',t:'Pizzeria Napoli (bezorging)',e:'🛵',c:['bestellen'],l:'rustig',m:['laagdrempelig','eten','binnen'],i:['eten','thuis'],io:'binnen',p:14,r:4.2,km:2.5,dur:35,h:[16,23.5],g:[1,20],b:0,di:['veg'],cu:'pizza',del:1,desc:'Napolitaanse pizza aan de deur binnen 35 minuten.',menu:['Margherita','Diavola','Quattro formaggi']},
{id:'thai',t:'Thai Orchid (bezorging)',e:'🍜',c:['bestellen'],l:'rustig',m:['laagdrempelig','eten','binnen'],i:['eten','thuis'],io:'binnen',p:16,r:4.4,km:3.0,dur:40,h:[16,22],g:[1,20],b:0,di:['veg','vegan','gluten'],cu:'thais',del:1,desc:'Pad thai, curry\'s en loempia\'s, bezorgd.',menu:['Pad thai','Groene curry','Tom kha']},
{id:'toro',t:'Steakhouse El Toro',e:'🥩',c:['uiteten'],l:'rustig',m:['luxe','eten','romantisch','binnen'],i:['eten'],io:'binnen',p:48,r:4.4,km:2.0,dur:150,h:[17,23],g:[2,12],b:1,cu:'steak',desc:'Dry-aged steaks van de grill.',menu:['Ribeye 300 g','Tomahawk','Crème brûlée']},
{id:'b1',t:'Bioscoopavond: nieuwste film naar keuze',e:'🍿',c:['bioscoop','activiteit'],l:'rustig',m:['gezellig','binnen'],i:['film'],io:'binnen',p:13,r:4.2,km:1.0,dur:130,h:[18,24],g:[1,20],b:1,lang:'Originele versie, NL ondertiteling',times:['19:15','21:30'],desc:'Kies samen een film uit het actuele programma van de bioscoop in de buurt.'},
{id:'t1',t:'Bordspelavond',e:'🧩',c:['thuis'],l:'rustig',m:['gezellig','competitief','laagdrempelig','binnen'],i:['thuis','games'],io:'binnen',p:3,r:4.5,km:0,dur:180,h:[0,48],g:[2,8],b:0,need:['2 à 3 spellen','Snacks','Grote tafel'],diff:'Makkelijk',pet:1,kid:1,desc:'Ieder neemt een spel mee. De winnaar kiest het volgende spel.'},
{id:'t2',t:'Pizza zelf maken',e:'👩‍🍳',c:['thuis','workshop'],l:'rustig',m:['gezellig','creatief','eten','binnen'],i:['thuis','eten','creatief'],io:'binnen',p:8,r:4.6,km:0,dur:150,h:[0,48],g:[2,10],b:0,need:['Bloem, gist, tomaten','Toppings per persoon','Oven'],diff:'Gemiddeld',pet:1,kid:1,di:['veg','vegan','halal','gluten','lactose'],desc:'Deeg kneden, zelf beleggen en een jury voor de mooiste pizza.'},
{id:'t3',t:'Pubquiz thuis',e:'❓',c:['thuis'],l:'rustig',m:['competitief','gezellig','binnen'],i:['thuis','games'],io:'binnen',p:2,r:4.3,km:0,dur:120,h:[0,48],g:[4,16],b:0,need:['Quizvragen (60 in de app)','Pen en papier'],diff:'Makkelijk',pet:1,kid:1,desc:'Zes rondes, teams van twee; de verliezer doet de afwas.'},
{id:'t4',t:'Cocktailavond thuis',e:'🍹',c:['thuis','borrel'],l:'rustig',m:['feestelijk','creatief','gezellig','binnen'],i:['thuis','eten'],io:'binnen',p:12,r:4.4,km:0,dur:180,h:[0,48],g:[2,10],b:0,alc:'req',age:18,need:['Shaker','Limoenen, munt, ijs','2 flessen sterke drank'],diff:'Makkelijk',pet:1,desc:'Iedereen bedenkt een signature cocktail en de groep stemt.'},
{id:'t5',t:'Karaoke thuis',e:'🎶',c:['thuis','uitgaan'],l:'licht',m:['feestelijk','muziek','gezellig','binnen'],i:['thuis','muziek'],io:'binnen',p:0,r:4.0,km:0,dur:120,h:[0,48],g:[2,12],b:0,need:['Tv met YouTube','Microfoon (optioneel)'],diff:'Makkelijk',pet:1,kid:1,desc:'Stel vooraf een lijst samen en kies per ronde een thema.'},
{id:'t6',t:'Pokeravond',e:'🃏',c:['thuis'],l:'rustig',m:['competitief','gezellig','binnen'],i:['thuis','games'],io:'binnen',p:5,r:4.2,km:0,dur:240,h:[0,48],g:[3,9],b:0,age:18,need:['Kaarten en fiches','Inleg €5 p.p.'],diff:'Gemiddeld',pet:1,desc:'Texas Hold\'em-toernooi met oplopende blinds.'},
{id:'t7',t:'Mario Kart-toernooi',e:'🎮',c:['thuis'],l:'rustig',m:['competitief','gezellig','binnen'],i:['thuis','games','tech'],io:'binnen',p:0,r:4.5,km:0,dur:120,h:[0,48],g:[2,8],b:0,need:['Console en 4 controllers','Snacks'],diff:'Makkelijk',pet:1,kid:1,desc:'Poules, knock-outfase en een zelfgemaakte beker.'},
{id:'t8',t:'Samen ramen koken',e:'🍲',c:['thuis','workshop'],l:'rustig',m:['gezellig','eten','creatief','binnen'],i:['thuis','eten','creatief'],io:'binnen',p:10,r:4.4,km:0,dur:150,h:[0,48],g:[2,8],b:0,need:['Bouillon, noedels, eieren','Toppings','Grote pan'],diff:'Gemiddeld',pet:1,di:['veg','halal','lactose'],desc:'De bouillon trekt al; iedereen maakt zijn eigen kom.'},
{id:'thermen',t:'Thermen Maasdal',e:'🧖',c:['wellness'],l:'rustig',m:['ontspannen','luxe','romantisch','binnen'],i:['wellness'],io:'beide',p:42,r:4.6,km:12,dur:240,h:[10,23],g:[1,12],b:1,age:16,desc:'Sauna\'s, buitenbaden en een rustzaal. Badjas inbegrepen.'},
{id:'mstr',t:'Dagje Maastricht',e:'🏰',c:['dagje'],l:'licht',m:['cultureel','gezellig','eten'],i:['reizen','cultuur','eten'],io:'beide',p:45,r:4.5,km:70,dur:480,h:[9,23],g:[1,20],b:0,acts:['Stadswandeling','Boekhandel in een kerk','Lunch op het Vrijthof'],over:0,wx:1,desc:'Met de trein naar Maastricht: wandelen, winkelen en vlaai.'},
{id:'zoo',t:'Dierenpark De Maasvallei',e:'🦒',c:['dagje','activiteit'],l:'licht',m:['kind','buiten','gezellig'],i:['dieren','familie'],io:'buiten',p:25,r:4.3,km:30,dur:300,h:[10,17],g:[1,30],b:0,kid:1,wx:1,acts:['Dierenshows','Speeltuin','Restaurant'],over:0,desc:'Savanne, apenbos en een grote speeltuin.'},
{id:'ardennen',t:'Weekend Ardennen-hut',e:'🏕️',c:['weekend','vakantie'],l:'actief',m:['avontuurlijk','buiten','gezellig'],i:['natuur','reizen'],io:'buiten',p:120,r:4.7,km:170,dur:2880,d:'56',h:[0,48],g:[2,10],b:1,over:1,wx:1,pet:1,acts:['Hiken','Kajakken','Kampvuur'],desc:'Houten hut bij Durbuy met hottub, twee nachten.'},
{id:'mystery',t:'Mystery dinner',e:'🎁',c:['verrassing','uiteten'],l:'rustig',m:['gezellig','spontaan','feestelijk','eten','binnen'],i:['eten'],io:'binnen',p:34,r:4.5,km:1.8,dur:180,d:'56',h:[18,23],g:[2,12],b:1,di:['veg','gluten'],desc:'Vijf verrassingsgangen. Je hoort pas aan tafel wat je eet.'},
{id:'rooftop',t:'Rooftopborrel Maaszicht',e:'🌇',c:['borrel','uitgaan'],l:'rustig',m:['gezellig','muziek','buiten'],i:['muziek','nacht','eten'],io:'beide',p:15,r:4.3,km:0.8,dur:150,d:'456',h:[16,26],g:[2,20],b:0,alc:'opt',pet:1,desc:'Dakterras met dj vanaf 20:00 en uitzicht over de Maas.'},
{id:'club',t:'Club Nachtwerk',e:'🪩',c:['uitgaan'],l:'licht',m:['feestelijk','muziek'],i:['nacht','muziek'],io:'binnen',p:15,r:4.0,km:1.0,dur:240,d:'56',h:[23,29],g:[1,40],b:0,age:18,alc:'opt',desc:'House en urban in twee zalen.'},
{id:'keramiek',t:'Keramiekworkshop',e:'🏺',c:['workshop','activiteit'],l:'rustig',m:['creatief','ontspannen','leerzaam','binnen'],i:['creatief'],io:'binnen',p:39,r:4.8,km:2.5,dur:150,d:'0346',h:[10,22],g:[2,10],b:1,desc:'Draaien op de schijf. Je werk wordt gebakken en na twee weken opgehaald.'},
{id:'vlot',t:'Teambuilding vlotbouwen',e:'🪵',c:['activiteit','sport'],l:'actief',m:['team','buiten','competitief'],i:['natuur','sport'],io:'buiten',p:35,r:4.4,km:8,dur:180,h:[9,18],g:[8,40],b:1,wx:1,w:0,desc:'Bouw met tonnen en touw een vlot en race over de plas.'},
];
OPTS.forEach(o=>{o.d??='0123456';o.w??=1;o.kid??=0;o.pet??=0;o.alc??='none';o.age??=0;o.di??=[];o.food=o.c.some(c=>FOODCATS.includes(c))||o.i.includes('eten')});
const PEOPLE={lisa:{n:'Lisa',col:'#7b4dff',taste:['games','eten','gezellig','competitief']},daan:{n:'Daan',col:'#0f9b74',taste:['sport','games','competitief','motor','actief']},sanne:{n:'Sanne',col:'#e0703a',taste:['eten','gezellig','cultuur','rustig','creatief']},noor:{n:'Noor',col:'#d63c78',taste:['romantisch','eten','film','ontspannen']},bram:{n:'Bram',col:'#2f7de1',taste:['scifi','thriller','film','games']},fleur:{n:'Fleur',col:'#c2410c',taste:['komedie','romantiek','film','gezellig']},joost:{n:'Joost',col:'#4b5563',taste:['misdaad','thriller','film','scifi']},mo:{n:'Mo',col:'#0e7490',taste:['eten','sport','games']},eva:{n:'Eva',col:'#9333ea',taste:['creatief','eten','gezellig']},tim:{n:'Tim',col:'#15803d',taste:['sport','natuur','avontuurlijk']}};
const FAV={pool:['lisa','daan','sanne'],f3:['bram','fleur','joost'],s1:['bram','joost']};
export const opt=id=>OPTS.find(o=>o.id===id)||TITLE_CACHE[id];
export {GENRE_IDS,STREAMS,SPEED,CATS,LVLS,LVLEX,MOODS,INTS,TRANS,REACH,DIETS,CUIS,GENRES,RULES,FOODCATS,GRAD,TITLES,QUICK,OPTS,PEOPLE,FAV};
